### ISSUE TITLE
是不是最好给个全局toggle function好点？

### ISSUE THREAD

**Issue by sonacy** [zthxxx/react-dev-inspector#1]
那个组合按键模式太长了，给全局挂个类似 window.__REACT_DEV_INSPECTOR_TOGGLE__()的方法更容易点。

**Comment by zthxxx** [comment]
OK 这两天加一下

另外组合按键是可以改的，从组件参数传进去，后两天周末我把文档也再补一下

**Comment by zthxxx** [comment]
- 增加了 `window. __REACT_DEV_INSPECTOR_TOGGLE__` 函数

- 增加了关于 props 的文档

v1.0.9
