### ISSUE TITLE
Inspector 开启 debug 悬浮，组件名称显示不兼容 react 17

### ISSUE THREAD

**Issue by nzreal** [zthxxx/react-dev-inspector#10]
![image](https://user-images.githubusercontent.com/56421380/103195282-ec75ff00-491c-11eb-85fe-e2f1f79a9ec6.png)
https://github.com/facebook/react/blob/master/packages/react-dom/src/client/ReactDOMComponentTree.js
17 版本以上 的 react-dom 的 instanceKey 已经更新成 __reactFiber$ 了

**Comment by zthxxx** [comment]
@nzreal  yes, `internalInstanceKey` was changed in [facebook/react#18377](https://github.com/facebook/react/pull/18377/files), which is merged into [react@16.14.0](https://github.com/facebook/react/blob/v16.14.0/packages/react-dom/src/client/ReactDOMComponentTree.js#L39)

i will fix it soon for compatibility

**Comment by zthxxx** [comment]
@nzreal  fixed in [react-dev-inspector@v1.1.2](https://www.npmjs.com/package/react-dev-inspector/v/1.1.2)

`npm i -D react-dev-inspector@^1.1.2`
