### ISSUE TITLE
visual indicator of dev-inspector is "active"

### ISSUE THREAD

**Issue by murugaratham** [zthxxx/react-dev-inspector#105]
First of all thanks for such an amazing project, i do have a suggestion that there should be a UI indicator or sorts, since currently, when i press the hotkey combination, if i don't move the mouse, i do not know that the inspector is active.

**Comment by murugaratham** [comment]
You mean I launch a separate react app and dev inspector concurrently?

**Comment by murugaratham** [comment]
![Screenshot 2021-11-01 at 11 27 16 AM](https://user-images.githubusercontent.com/653805/139617792-3f001c9d-79f8-4e49-afb7-bf13fec134f1.png)

I can run directly in examples/cra (in my case), but also noticed that it's from es folder, what's your dev workflow like?

**Comment by zthxxx** [comment]
> 1. record latest mouse moved point after inspector component mounted
> 2. when press the hotkey, inspect and show tooltip of DOM at mouse point immediately

will make sure show inspector tooltip immediately while press the hotkey

**Comment by murugaratham** [comment]
Alright, thanks @zthxx, I'll not try to fork n run while waiting for your next release

**Comment by zthxxx** [comment]
> ![Screenshot 2021-11-01 at 11 27 16 AM](https://user-images.githubusercontent.com/653805/139617792-3f001c9d-79f8-4e49-afb7-bf13fec134f1.png)
> 
> I can run directly in examples/cra (in my case), but also noticed that it's from es folder, what's your dev workflow like?

`npm run site cra`

**Comment by murugaratham** [comment]
I get the same nodemon looping indefinitely, is there any npm global tools needed?

**Comment by zthxxx** [comment]
npm version > v7 for dev

**Comment by murugaratham** [comment]
Managed to get it to work, although i had this

![Screenshot 2021-11-01 at 11 56 58 AM](https://user-images.githubusercontent.com/653805/139620180-9d8c1d63-6707-42df-8579-8eb4bd995474.png)

Overcame by setting NODE_OPTIONS `export NODE_OPTIONS=--openssl-legacy-provider; npm run site cra`

And for me to get latest `Inspector.tsx`, i need to `npm run build` everytime?

**Comment by zthxxx** [comment]
`npm run dev` for common dev (build lib & watch files & website)

`npm run site cra` for only start dev for cra site
