### ISSUE TITLE
这个库能实现错误代码定位吗？

### ISSUE THREAD

**Issue by a982564562** [zthxxx/react-dev-inspector#109]
如题，页面报错时能回到ide中出错文件的位置吗？

**Comment by zthxxx** [comment]
@a982564562  你说的是 react 默认就有的吧

**Comment by a982564562** [comment]
> @a982564562 你说的是 react 默认就有的吧

https://github.com/facebook/create-react-app/blob/c7627ce96c4674f327081f101dd0e2771be4d045/packages/react-error-overlay/src/containers/StackFrame.js
是的，它的源码里有个点击事件的判断，我在你的源码里没找到

**Comment by zthxxx** [comment]
所以需要这个功能的话，react 默认就有， react-dev-inspector 就没必要做了
