### ISSUE TITLE
inspectorChainWebpack 's chain operate: i think it's better to add 'enforce('pre')'

### ISSUE THREAD

**Issue by nzreal** [zthxxx/react-dev-inspector#11]
![image](https://user-images.githubusercontent.com/56421380/103272730-8e1e4e80-49f8-11eb-8f6c-57507f2819f8.png)
the inspector-loader must be before jsx babel-loader

**Comment by zthxxx** [comment]
close in https://github.com/zthxxx/react-dev-inspector/commit/419e89cd0efc8ab73ff79206fbd61abbaacea52e

**Comment by zthxxx** [comment]
@nzreal  [react-dev-inspector@1.1.3](https://www.npmjs.com/package/react-dev-inspector/v/1.1.3)
