### ISSUE TITLE
考虑支持 esbuild 吗

### ISSUE THREAD

**Issue by suchangv** [zthxxx/react-dev-inspector#116]
项目编译 js 部分最近会整体从 babel 迁移至 esbuild，打包还是用 webpack，作者考虑支持 esbuild 吗？

**Comment by zthxxx** [comment]
esbuild 没法支持，如果你用 vite 的话，实际上 vite 还是会用 babel 编译一遍 jsx/tsx 源码所以可用，纯 esbuild 没有 ast 扩展能力， swc 才有可能
