### ISSUE TITLE
relativePath will be wrong in monorepo or lerna repo

### ISSUE THREAD

**Issue by nzreal** [zthxxx/react-dev-inspector#12]
![image](https://user-images.githubusercontent.com/56421380/103273146-94f99100-49f9-11eb-8f82-14a227bf134f.png)

but the real filePath is /.../project-root/packages/pc-components/src/components/app-card/index.tsx

if u need a demo repo, i will offer it to u later

**Comment by zthxxx** [comment]
@nzreal  thanks, and I really need a demo repo

**Comment by nzreal** [comment]
@zthxxx  https://github.com/nzreal/monorepo-test

**Comment by zthxxx** [comment]
close in https://github.com/zthxxx/react-dev-inspector/commit/c9d3c1e2c65b2c651406796e65ead8cb1bc3550e

react-dev-inspector@1.1.4
