### ISSUE TITLE
默认打开sublime 怎么使其默认打开vscode

### ISSUE THREAD

**Issue by Rickiiii** [zthxxx/react-dev-inspector#126]
默认打开sublime 怎么使其默认打开vscode

**Comment by zthxxx** [comment]
<img width="654" alt="image" src="https://user-images.githubusercontent.com/15135943/170425356-ae58f68d-7582-44ca-8383-af1b16a47d5e.png">

这个配置太麻烦了，有计划直接改成只支持 vscode，走 url  不再配置

**Comment by Rickiiii** [comment]
我设置了一遍zsh 并且source过了 还是打开sublime 我把sublime进程删除后 才打开vscode

**Comment by zthxxx** [comment]
@Rickiiii    直接使用 component 配置如下，不需要在有任何  babel/webpack/server 配置

```ts
<Inspector
  disableLaunchEditor={true}
  onClickElement={(inspect: InspectParams) => {
    const {
      absolutePath,
      lineNumber,
      columnNumber,
    } = inspect.codeInfo ?? {}

    if (!absolutePath) return

    window.open(`vscode://file/${absolutePath}:${lineNumber}:${columnNumber}`)
  }}
/>
```

**Comment by zthxxx** [comment]
@Rickiiii 在 README 文档中也更新了使用说明

<img width="974" alt="image" src="https://user-images.githubusercontent.com/15135943/173633725-5a4ebd6f-8e8a-4991-9e1a-0992a4d5df6b.png">
