### ISSUE TITLE
@babel/types should be listed in dependencies instead of devDependencies

### ISSUE THREAD

**Issue by heiseshandian** [zthxxx/react-dev-inspector#127]
Currently, in `src/plugins/babel/visitor.ts`, we directly use the utils imported from `@babel/types/lib/builders/generated`, which means `@babel/types/lib/builders/generated` is not only needed during development, we should put it under `dependencies` instead of `devDependencies`.

```ts
import {
  jsxAttribute,
  jsxIdentifier,
  stringLiteral,
} from '@babel/types/lib/builders/generated'
//...

const lineAttr: JSXAttribute | null = isNil(line)
    ? null
    : jsxAttribute(
      jsxIdentifier('data-inspector-line'),
      stringLiteral(line.toString()),
    )
```

**Comment by zthxxx** [comment]
@heiseshandian  Sorry for wait, I have not noticed this issue's notification, now it fixed in [react-dev-inspector@1.8.1](https://www.npmjs.com/package/react-dev-inspector/v/1.8.1)
