### ISSUE TITLE
It might be unnecessary to setup an extension to open files in VS Code.

### ISSUE THREAD

**Issue by EnixCoda** [zthxxx/react-dev-inspector#129]
This project is creative! Perhaps it can get rid of the extension for VS Code users to simplify the workflow.

VSCode sets up the `vscode://` protocol handler that works in browsers. URLs that starts with `file` will be handled as `Open file` command.
For example, a link with the URL `vscode://file/Users/username/Downloads/test.txt` would open `/Users/username/Downloads/test.txt` for you, if it exists on your drive.

**Comment by zthxxx** [comment]
Yes, you are right, here's a project with the same idea [`click-to-component`](https://github.com/ericclemmons/click-to-component)

Additionally, `react-dev-inspector` can also  config like this behavior for **vscode only**

```ts
<Inspector
  disableLaunchEditor={true}
  onClickElement={(inspect: InspectParams) => {
    const {
      absolutePath,
      lineNumber,
      columnNumber,
    } = inspect.codeInfo ?? {}

    if (!absolutePath) return

    window.open(`vscode://file/${absolutePath}:${lineNumber}:${columnNumber}`)
  }}
/>
```

**Comment by zthxxx** [comment]
@EnixCoda  thanks for proposal, I have updated the docs.

<img width="974" alt="image" src="https://user-images.githubusercontent.com/15135943/173633725-5a4ebd6f-8e8a-4991-9e1a-0992a4d5df6b.png">
