### ISSUE TITLE
How to use this awesome stuff in gatsbyjs ?

### ISSUE THREAD

**Issue by lwyj123** [zthxxx/react-dev-inspector#13]
I have try https://www.gatsbyjs.com/docs/how-to/custom-configuration/add-custom-webpack-config/ but didn't work.

**Comment by lwyj123** [comment]
I just figure it out...

**Comment by zthxxx** [comment]
@lwyj123  could you show your solution code?

**Comment by lwyj123** [comment]
@zthxxx I just modified gatsby-node.js like below

**Comment by zthxxx** [comment]
thanks for demo
