### ISSUE TITLE
功能需求: umi4 支持    [v1.8.6 已支持]

### ISSUE THREAD

**Issue by xiefengnian** [zthxxx/react-dev-inspector#132]
react-dev-inspector/plugins/umi/react-inspector 需要支持 umi4

**Comment by zthxxx** [comment]
@xiefengnian 没用 umi4，有空看看； 或者你来提个 PR 不？🌝

**Comment by xiefengnian** [comment]
> @xiefengnian 没用 umi4，有空看看； 或者你来提个 PR 不？🌝

升一个大版本 or 搞一个 plugins/umi4

**Comment by JamieMing** [comment]
看了代码，github上的源码应该是支持umi4的，但是npm上的产物代码并不一致，是直接调用了modifyBabelOpts，但umi4取消了这个方法，而作者github代码上是已经做了判断处理的。希望作者可以更新一下npm上的代码~

**Comment by JamieMing** [comment]
我现在是直接将react-inspector的代码拉了一份出来，在plugins配置中引入，并去掉参数设置（因为会报错），即可

**Comment by zthxxx** [comment]
@xiefengnian  @JamieMing 有 PR 合并了兼容 umi4 的代码，之前发版失败了，现在已经重新发到 [v1.8.2](https://www.npmjs.com/package/react-dev-inspector/v/1.8.2) 的版本上了

**Comment by Yyunfan** [comment]
@zthxxx 哈喽，plugins\umi\react-inspector.js#L50， umi的api拼错了，应该是addBeforeMiddlewares

**Comment by zthxxx** [comment]
@Yyunfan 这个 typo 是旧版 umi 自己提供 api 就写错了的

**Comment by zthxxx** [comment]
@Yyunfan  这个 api 加了兼容处理了，发到 [1.8.3](https://www.npmjs.com/package/react-dev-inspector/v/1.8.3) 版本了

**Comment by Yyunfan** [comment]
@zthxxx 修复了typo错误后，仍然会报错，TypeError: Cannot read property 'register' of undefined，貌似这次更新还影响到隔壁ant-design-pro库的使用，也会报这个错

**Comment by zthxxx** [comment]
@Yyunfan  抱歉，发布了 `1.8.4` 回滚到 `1.8.1` 的版本了，umi4 的支持本周末仔细看看

**Comment by ado5** [comment]
期待更新

**Comment by ado5** [comment]
vite4 什么时候能也支持一下？

**Comment by baikaifa** [comment]
这个解决完了吗？我尝试了还是不行，文档上要不补充下umi4怎么用。

**Comment by GitHdu** [comment]
还未支持

**Comment by GitHdu** [comment]
> 我现在是直接将react-inspector的代码拉了一份出来，在plugins配置中引入，并去掉参数设置（因为会报错），即可

怎么引入的，有例子吗

**Comment by zthxxx** [comment]
发版了，试试 `v1.8.6`

尝试支持了 umi4 的 addBeforeBabelPlugins api

**Comment by Yyunfan** [comment]
ok，umi4确实可以使用了  👍
