### ISSUE TITLE
今天升级了包 umi3打包失败，昨天是正常的

### ISSUE THREAD

**Issue by CoderBOBO** [zthxxx/react-dev-inspector#136]
![lQLPJx9iUupBFZzNBEjNCfCwwKRpPkAaYqADjeFEEABHAA_2544_1096 png_620x10000q90](https://user-images.githubusercontent.com/12329078/206420576-c956d634-0c6b-4d68-9440-5735ec3d0863.jpg)

**Comment by xiaowenxia** [comment]
我也碰到了，指定 `1.6.0` 版本能 work 。

**Comment by luoyepiaoling123** [comment]
发布的1.8.3 版本有问题，使用1.8.2正常了，希望作者尽快修复

**Comment by zthxxx** [comment]
@luoyepiaoling123  @CoderBOBO @xiaowenxia  非常抱歉

 published `v1.8.4`  as a revert to `v1.8.1`
