### ISSUE TITLE
引入了react-dev-inspector后，我的测试通过不了？

### ISSUE THREAD

**Issue by alexya** [zthxxx/react-dev-inspector#14]
refer to: 
https://v2ex.com/t/746186

大神，我引用了你的这个库之后，原先能够通过的测试，就没有办法通过了。能帮忙瞧一下，哪里配置出了问题么？

谢谢

**Comment by zthxxx** [comment]
@alexya  jest 如果要跑 jsx / tsx 文件，最好也编译一下，保证和 webpack loader 处理后一致，如 jest 有 transform 字段配置，通常会配置 ts-jest 和 babel

https://jestjs.io/docs/en/configuration#transform-objectstring-pathtotransformer--pathtotransformer-object

**Comment by zthxxx** [comment]
或者在 jest 环境下就不去 import 这个库呢，

因为这个库导出的给 react 的组件是 ES module 类型的 (导出的给 node 用的 plugin 这些才是 commonjs 的)，

所以目前在你的 jest 下如果不经过 babel / esm 这些转换就不支持
