### ISSUE TITLE
vite 4.x 中使用 @vitejs/plugin-react-swc 插件，编译报错

### ISSUE THREAD

**Issue by yaojiadong666** [zthxxx/react-dev-inspector#145]
![image](https://user-images.githubusercontent.com/105629090/233524971-df43e332-c377-45dc-a5ba-ffd878368b4d.png)

考虑支持  @vitejs/plugin-react-swc 插件吗？

**Comment by zthxxx** [comment]
在 vite4 中，不加 react-dev-inspector 的 babel plugin 也一样可以用的
