### ISSUE TITLE
vite4中获取的行数并不准确

### ISSUE THREAD

**Issue by jokeran163** [zthxxx/react-dev-inspector#146]

**Comment by zthxxx** [comment]
具体是什么样？

**Comment by renhh** [comment]
我使用import react from '@vitejs/plugin-react-swc'; 之后，可以通过快捷键进行跳转，但是为什么在控制台检查元素时看不到对应的路径和行数呢？react版本 > 18

**Comment by zthxxx** [comment]
@renhh DOM 元素上的路径属性对于跳转不是必须的，实际会用的是 react fiber 中记录的路径；

**Comment by renhh** [comment]
> @renhh DOM 元素上的路径属性对于跳转不是必须的，实际会用的是 react fiber 中记录的路径；

我的需求是想看到DOM 元素上的路径😂，大佬有什么办法吗？

**Comment by renhh** [comment]
我使用 @vitejs/plugin-react 的配置的时候是可以看到 DOM元素上面的路径的，换到 @vitejs/plugin-react-swc 看不到了

**Comment by zthxxx** [comment]
@renhh 
- 鼠标右键显示 DOM 结构以及路径 (>=v2.1.0)

<img width="561" alt="image" src="https://github.com/user-attachments/assets/e20bb800-1c89-4ed1-8ac3-f02ac667825c">

- 浏览器插件 [React Developer Tools](https://react.dev/learn/react-developer-tools)

<img width="500" src="https://github.com/user-attachments/assets/6020d023-4ecb-41f4-9fd8-48defd9a9c76" />

**Comment by renhh** [comment]
好的，感谢
