### ISSUE TITLE
Can inspector jump to the place custum components referenced but not it defined

### ISSUE THREAD

**Issue by nzreal** [zthxxx/react-dev-inspector#15]
As the title say, when i inspect and click
![image](https://user-images.githubusercontent.com/56421380/105271066-d41e9a80-5bd1-11eb-86cd-b75bbb0f0259.png)
I will jump here 
![image](https://user-images.githubusercontent.com/56421380/105271116-e993c480-5bd1-11eb-885f-ae8d6c0fbb85.png)
But don't u think jump to the place it referenced is better ? Or just add the new way of jump
![image](https://user-images.githubusercontent.com/56421380/105271276-2cee3300-5bd2-11eb-9f3e-e17c066dbfc9.png)

**Comment by zthxxx** [comment]
@nzreal   <ove your mouse more close to the text `Ctrl ^`, like this:

![image](https://user-images.githubusercontent.com/15135943/105275111-873ec200-5bd9-11eb-8bed-21fd1aec3be3.png)

NOT the button which wrapped in text `Ctrl ^`, like this:

![image](https://user-images.githubusercontent.com/15135943/105275253-d5ec5c00-5bd9-11eb-97c1-aaa9b4f35073.png)

In this above, your intention of mouse is "hi, show me the code of the button", it isn't "hi, show me the place of the text", so the behavior of jump is all right.

More exactly, this reason why this appearance is "two components nested，and their border(or padding) are overlapped", so your mouse should move carefully,

Some better solution maybe click to popover components's name list to confirm (by click name in list) if they are overlapped.

**Comment by nzreal** [comment]
that's just a special example, the reason why u can jump to the place referenced is the div tag in Keypress record the info where it is 
![image](https://user-images.githubusercontent.com/56421380/105277411-53b26680-5bde-11eb-8d21-7d9f90a203aa.png)
but in most cases, clicking the comps can not jump to the place of reference
 i  practice the inspector in real development to draw this conclusion, so i wanna talk about this with u to find out is there any best way to optimize it

**Comment by nzreal** [comment]
and in extreme case, a comp as this 
`
const App = (props) => {
    <div {...props}></div>
}
`
to desconstructe the rest props in root node 
it can let us jump to the place of reference

**Comment by zthxxx** [comment]
@nzreal  yes, got it,

but sorry for current Implementation method (by babel in compile), will make the inspect not "perfectly accurate", so I design it for "UI components" as entry point (not business components), and I thinks it's maybe basic enough at that time, and other reasons are here:

- it inspired by Chrome inspector and design to imitate Chrome inspector, for inspect DOM which written in our project, but not in third-party libs (like in node_modules)
- "perfectly accurate" inspect is too complex to use, similar to use Chrome inspector, most time we always need open "Chrome DevTools - Elements" and find in DOM tree, because it CANNOT really inspect anyone in webpage while their boundaries overlap each other.
- I've thought about inject `React.createElement` to cooperate with inject some info in runtime, (can deal the extreme case you mentioned), but as said above, too complex to interaction

**Comment by zthxxx** [comment]
to be frank, I don't know a better way to do it  ☹️

**Comment by nzreal** [comment]
neither do i , i think there are 2 ways,

1. as u say, inject React.createElement
2. wrap every comp with span tag in compile(the premise is no influence to dom style)

but all this ways carry risks

**Comment by zthxxx** [comment]
@nzreal yes, both of 2 ways are not good

1. cannot inject if someone use other jsxFactory like emotion.jsx
2. it's too invasive, and will obviously break structure both of css or html

**Comment by nzreal** [comment]
@zthxxx bro, i've find a way to jump to place of reference, after testing can i pull requests ?

**Comment by zthxxx** [comment]
@nzreal  yes, you are welcome, and could you describe what you find?

**Comment by nzreal** [comment]
![image](https://user-images.githubusercontent.com/56421380/108506001-221edf00-72f3-11eb-90f8-29c2c02072ab.png)
![image](https://user-images.githubusercontent.com/56421380/108506049-32cf5500-72f3-11eb-8347-962d66d30304.png)
in dev-tools,it can record the runtime props, i've find how to get it
what do u think of whether should we keep the ability to jump to the place of definition

**Comment by nzreal** [comment]
@zthxxx https://github.com/zthxxx/react-dev-inspector/pull/20/files

**Comment by zthxxx** [comment]
react-dev-inspector@1.2.0

**Comment by zthxxx** [comment]
react-dev-inspector@1.3.1
