### ISSUE TITLE
获取不到absolutePath

### ISSUE THREAD

**Issue by tututuanzinuomi** [zthxxx/react-dev-inspector#150]
问题描述，用的umi3，且有[@babel/plugin-transform-react-jsx-source]
![image](https://github.com/zthxxx/react-dev-inspector/assets/141313899/57f14ee4-130b-4419-806e-2bc21360bf70)
![image](https://github.com/zthxxx/react-dev-inspector/assets/141313899/8879ebdc-949f-4f37-816d-b22d0b30b032)
获取不到absolutePath，有遇到相同问题的吗，很疑惑不知道是哪的问题

**Comment by zthxxx** [comment]
react-dev-inspector 自己的 babel-plugin 是处理相对路径的，并且优先级更高，
因此把 react-dev-inspector 的 babel-plugin 去掉就会读默认绝对路径了。

另外问下相对路径用起来有问题么？

**Comment by gikey** [comment]
> 

如果不使用 react-dev-inspector 的 babel plugin 节点中就不会添加相对路径了，有点不方便，能尽快解决下吗 @zthxxx

**Comment by zthxxx** [comment]
@gikey  你遇到的是什么问题，绝对路径用起来有区别吗？听你描述应该和这个 issue 本身是反的吧
