### ISSUE TITLE
codeInfo 何时返回绝对路径 何时返回相对路径啊

### ISSUE THREAD

**Issue by wangjianjia1314** [zthxxx/react-dev-inspector#151]
在两个工程里同时使用。都是umi3+ 没有任何其他配置。其中一个返回的是相对路径 一个返回的是绝对路径，请问这是为什么，如何让相对路径返回的是绝对路径啊

**Comment by zthxxx** [comment]
react-dev-inspector 自己的 babel-plugin 是处理相对路径的，并且优先级更高，
因此把 react-dev-inspector 的 babel-plugin 去掉就会读默认绝对路径了。

另外问下相对路径用起来有问题么？
