### ISSUE TITLE
生产环境下，不应该打包进js文件

### ISSUE THREAD

**Issue by chen2938** [zthxxx/react-dev-inspector#152]
如题，使用webpack5，在webpack.dev.js配置后，发现npm run build，使用webpack的分析插件，发现仍然存在react-dev-inspector

**Comment by zthxxx** [comment]
给一下项目里组件使用代码和 webpack 配置呢？

按照示例写法的话，prod 下不会用到因而被 tree-shaking 去掉

**Comment by NewFuture** [comment]
按照文档上的方式，发现了同样的问题，Inspector永远会打包进去

click-to-component 的实现是加了一个`process.env.NODE_ENV === 'development'`判断
https://github.com/ericclemmons/click-to-component/blob/67721921ad80090ff76ea63ef93cbd676c749561/packages/click-to-react-component/src/index.js#L2-L4

但是这里没有发现类似逻辑 https://github.com/zthxxx/react-dev-inspector/tree/dev/packages/inspector/src/Inspector

**Comment by zthxxx** [comment]
因为我的场景需要 production 下也能使用，所以不能内置这个判断 (例如构建 Devtool 库和 [文档站的Showcase](https://react-dev-inspector.zthxxx.me/showcase))。

它只会在 production 下默认 disable 不起任何作用，同时又因为整个包很轻量，运行时只有一个 `hotkeys-js` 的依赖，体积相当小，所以在我这里没啥问题。

但你在使用的时候完全可以做同样的处理，比如

```tsx
import { Inspector as InspectorComponent } from 'react-dev-inspector'

const Inspector = process.env.NODE_ENV === 'development'
  ? InspectorComponent
  : Fragment

...

<Layout>
  <Inspector />
  <App />
</Layout>
```

也可以是

```tsx
import { Inspector } from 'react-dev-inspector'

<Layout>
  {(process.env.NODE_ENV === 'development') && <Inspector />}
  <App />
</Layout>
```

**Comment by NewFuture** [comment]
@zthxxx 是的，同时需要把webpack Babel plugin 去掉，不然会有很多 data-inspector.

**Comment by zthxxx** [comment]
@NewFuture 嗯嗯，这个在文档里也说了是 OPTIONAL 可选的，通常不需要加，
只是出于我需要的一些展示美观性上的需求我才加上的；

https://react-dev-inspector.zthxxx.me/docs/compiler-plugin

准备下一版里给 babel plugin 加上在 production 下自动默认 disable

**Comment by chen2938** [comment]
> @NewFuture 嗯嗯，这个在文档里也说了是 OPTIONAL 可选的，通常不需要加， 只是出于我需要的一些展示美观性上的需求我才加上的；
> 
> https://react-dev-inspector.zthxxx.me/docs/compiler-plugin
> 
> 准备下一版里给 babel plugin 加上在 production 下自动默认 disable

请问在v2版本更新了吗？由于某种原因我无法在现有项目中升级v2，也暂时无法提供配置示例，如果这个问题解决了，我将关闭这个issue

**Comment by zthxxx** [comment]
@chen2938  这个打包 JS 目前需要手动改成以下使用方式，v1/v2 版都是：(我会在文档中补充一下说明)



```tsx
import { Inspector } from 'react-dev-inspector'

<Layout>
  {(process.env.NODE_ENV === 'development') && <Inspector />}
  <App />
</Layout>
```
