### ISSUE TITLE
需要使用 swc 版本的插件吗？

### ISSUE THREAD

**Issue by LaamGinghong** [zthxxx/react-dev-inspector#153]
项目里面没有用 babel，可以提供一份 swc 版本的插件吗

**Comment by zthxxx** [comment]
babel 插件不是必须的，可以尝试不加 babel 插件直接使用 react 组件；

常用框架其实都默认配置了 babel 或 swc 都自带这个信息的，而且都是**绝对路径**，

react-dev-inspector 自己的 babel 插件只是为了 _简短好看便于观测_，才在 DOM 上加**相对**路径；

**Comment by LaamGinghong** [comment]
![image](https://github.com/zthxxx/react-dev-inspector/assets/33472924/10090197-4f3c-46e7-8229-5f16daf04bdf)
![image](https://github.com/zthxxx/react-dev-inspector/assets/33472924/59a35989-447c-4b10-9082-4bfacdbd93a9)
WebStorm 打开不了文件

**Comment by LaamGinghong** [comment]
![image](https://github.com/zthxxx/react-dev-inspector/assets/33472924/cbee76d0-36b0-443d-8286-b3b27908ba3c)
webstorm 得这样写

**Comment by zthxxx** [comment]
服务端唤起方式的话，CloudIDE 上给你项目里这样配置可以了， 留存一份截图；

> 本地的话 REACT_EDITOR 环境变量值换成 webstorm 再启动就行 
>
> (还需要重启 shell 或 WebStorm 本身以加载新的 zshrc 文件改动)


<img width="1216" alt="image" src="https://github.com/zthxxx/react-dev-inspector/assets/15135943/c14c1ec8-c027-4ef4-aee5-5ab592d29af0">
