### ISSUE TITLE
react-dev-inspector@2.0.0 Inspector component onClientElement cannot get codeInfo

### ISSUE THREAD

**Issue by rexhang** [zthxxx/react-dev-inspector#156]
```bash
"react-dev-inspector": "^2.0.0",
"@react-dev-inspector/middleware": "^2.0.0",
```

---

以上版本中：

发现2个问题，

![Snipaste_2023-10-27_18-57-03](https://github.com/zthxxx/react-dev-inspector/assets/14832793/6f7fef6c-72e6-4c05-a6d3-f36b5d98cac7)

![Snipaste_2023-10-27_18-50-20](https://github.com/zthxxx/react-dev-inspector/assets/14832793/f3cc04d8-74cd-4da5-ad47-e6644afba669)

快捷键激活后，点击DOM元素：

1. `onInspectElement` 事件不会触发
2. 只有 `onClickElement` 事件会触发，但触发后 在函数回调中拿到的 `codeInfo` 打印出来 永远都是 `undefined`，导致无法打开编辑器

期待得到解答~~

**Comment by zthxxx** [comment]
@rexhang  `codeInfo` 确实可能是 `undefined`，符合类型定义；

<img width="513" alt="image" src="https://github.com/zthxxx/react-dev-inspector/assets/15135943/f7f22788-d7dc-4605-80f6-8f8f50f68ac3">

原因可能是缺少默认的编译时路径注入，考虑配置: https://react-dev-inspector.zthxxx.me/docs/compiler-plugin

**Comment by rexhang** [comment]
> @rexhang `codeInfo` 确实可能是 `undefined`，符合类型定义；
> 
> <img alt="image" width="513" src="https://user-images.githubusercontent.com/15135943/278655520-f7f22788-d7dc-4605-80f6-8f8f50f68ac3.png">
> 原因可能是缺少默认的编译时路径注入，考虑配置: https://react-dev-inspector.zthxxx.me/docs/compiler-plugin

官方可以试下 在web多端的 [taro3](https://taro-docs.jd.com/docs/) 框架中，用React语言编写web端H5 demo，如何集成使用。给到案例，谢谢了。
