### ISSUE TITLE
Duplicate with the official devtool feature?（官方的 Devtool 是否已经实现类似功能）

### ISSUE THREAD

**Issue by sudo888samewick** [zthxxx/react-dev-inspector#157]
请参阅这个链接
https://github.com/facebook/react/pull/22649

官方2021年末的一个 pr ，它实现的功能是不是跟您的项目类似；二者有哪些异同 😄

**Comment by zthxxx** [comment]
I cannot find "open in editor" button, and it seems to only works in `StrictMode` without any error.

<img width="170" alt="image" src="https://github.com/zthxxx/react-dev-inspector/assets/15135943/ca298300-baa9-4be7-97f3-af729c9ba288">
