### ISSUE TITLE
Inspector plugin navigation question  |  关于 Inspector 插件跳转位置的使用

### ISSUE THREAD

**Issue by jrr997** [zthxxx/react-dev-inspector#158]
我在使用中遇到的问题：
	前端项目一般会有一个存放公共组件的文件夹(例如 `src/components`)。如果我在业务组件中使用了一个公共组件(例如`/src/components/MyButton`)。使用插件进行跳转时会跳到 `/src/components/MyButton`，期望的结果是跳到业务组件。

我看了文档，没找到相关的解决方法，请问目前 `react-dev-inspector` 可以实现我期待的结果吗。

**Comment by zthxxx** [comment]
与 #160 相同 Feature Request, in the plan
