### ISSUE TITLE
新版本vscode中，打不开指定文件了

### ISSUE THREAD

**Issue by xccjk** [zthxxx/react-dev-inspector#159]
vscode升级到最新版后，使用快捷键还是可以选择页面内容，但是打不开vscode对应文件了

vscode版本信息：

版本: 1.84.2 (Universal)
提交: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
日期: 2023-11-09T10:52:33.687Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.1.0

**Comment by xccjk** [comment]
试了下需要改成这样：

```

```

**Comment by luckymore** [comment]
[vscode 的 bug](https://github.com/microsoft/vscode/issues/197319) 已经在 Insider 版本修复了

下个发版日期，大概是明天，也可能会变
> 12/06 Expected release date (this may change)
