### ISSUE TITLE
Feature Request: Adding an option to view or open the parent element.

### ISSUE THREAD

**Issue by amirrezaDev1378** [zthxxx/react-dev-inspector#160]
In some scenarios where there are multiple parent elements and they all have the same width and height we are unable to select the desired element; it would be great if we could open a list parent element and open one ( Like locator js )

**Comment by zthxxx** [comment]
yes, in the plan

**Comment by zthxxx** [comment]
- right-click panel added in beta version `>= 2.1.0-beta.9` in PR #174
- `npm i -D react-dev-inspector@v2.1.0-beta.9`

![inspect-context-panel.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/aUDE86v77YXL5IaPeqiP/f13fef86-3b47-4ceb-8edf-7f9b125a1846.png)
