### ISSUE TITLE
webstorm 的代码跳转方法已经过时

### ISSUE THREAD

**Issue by miniocean404** [zthxxx/react-dev-inspector#161]
在我本地测试 webstorm://open?file=xx 的方式已经无法跳转了

**Comment by 729993031** [comment]
要安装以下插件
https://plugins.jetbrains.com/plugin/19991-ide-remote-control
通过 
http://localhost:63342/api/file/* 来跳转

**Comment by miniocean404** [comment]
> 要安装以下插件 https://plugins.jetbrains.com/plugin/19991-ide-remote-control 通过 http://localhost:63342/api/file/* 来跳转

但是他源代码里不是这么写的跳转方式啊

**Comment by zthxxx** [comment]
@MiniOcean404 hello, 系统版本与 WebStorm 版本多少？无法跳转的报错和现象截图也发一下吧，

另外我在本机 macOS 13.6/12.6  最新版 WebStorm 2023.2.5 上测试还是可以跳转。

**Comment by miniocean404** [comment]
webstorm 版本 2023.3.2
pc: windows 11
代码跳转方式：webstorm://open?file=D:/xx/xx/xx/xx/index.html

**Comment by 729993031** [comment]
mac是不需要插件的，win才需要
