### ISSUE TITLE
Path issues in Windows Vite React project   |   windows的vite的react项目中路径不太对，而且希望能加个绝对路径的，把path和Line和column合起来

### ISSUE THREAD

**Issue by baikaifa** [zthxxx/react-dev-inspector#173]
![image](https://github.com/zthxxx/react-dev-inspector/assets/26021374/3a08b492-3139-4e90-8f39-3ffd917d65ff)

**Comment by zthxxx** [comment]
- 把 `@react-dev-inspector/babel-plugin` 插件去掉，直接使用一框架自带的 [`@babel/preset-react`](https://react-dev-inspector.zthxxx.me/docs/compiler-plugin#babelpreset-react) / [`SWC`](https://react-dev-inspector.zthxxx.me/docs/compiler-plugin#swc) / [`esbuild`](https://react-dev-inspector.zthxxx.me/docs/compiler-plugin#esbuild) 就是绝对路径
- 如果有相对路径，则相对路径在显示优先级上更高，会优先显示相对路径
- Docs: https://react-dev-inspector.zthxxx.me/docs/compiler-plugin#react-dev-inspectorbabel-plugin

---

- 添加了右键菜单显示组件层级结构，并且把 path 和 lines 合并显示的，同时支持 hover 后点击复制
- right-click panel added in beta version `>= 2.1.0-beta.9`, PR #174
- `npm i -D react-dev-inspector@v2.1.0-beta.9`
- Online [Showcase Page](https://react-dev-inspector.zthxxx.me/showcase)

![inspect-context-panel.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/aUDE86v77YXL5IaPeqiP/f13fef86-3b47-4ceb-8edf-7f9b125a1846.png)
