### ISSUE TITLE
只支持webpack-dev-server，是否支持 自定义开发"webpack-dev-middleware"开发服务器？

### ISSUE THREAD

**Issue by pidehen23** [zthxxx/react-dev-inspector#18]
react-dev-inspector文档说明：
![image](https://user-images.githubusercontent.com/41351722/106579816-1b1a7180-657c-11eb-9f09-520f51ba87e0.png)
webpack-dev-middleware + express（不会跳转）
![image](https://user-images.githubusercontent.com/41351722/106580201-95e38c80-657c-11eb-9f74-c5b26d7bd8ac.png)

**Comment by chenjiajing23** [comment]
调整了中间件的位置之后就可以了，🤩
![image](https://user-images.githubusercontent.com/41351722/106580965-4ce00800-657d-11eb-979a-f2a30756d66d.png)

**Comment by zthxxx** [comment]
嗯，就像你改的这样，是支持的， 比如 umi 自己也是 `webpack-dev-middleware` 做的，但是需要自己保证顺序

**Comment by chenjiajing23** [comment]
> 嗯，就像你改的这样，是支持的， 比如 umi 自己也是 `webpack-dev-middleware` 做的，但是需要自己保证顺序

建议更新一波文档。

**Comment by zthxxx** [comment]
文档结构正在更新中

**Comment by zthxxx** [comment]
文档中目前添加了 `webpack-dev-middleware` 使用例子  https://react-dev-inspector.zthxxx.me/docs/integration#usage-examples

---

<img width="642" alt="Screenshot" src="https://github.com/zthxxx/react-dev-inspector/assets/15135943/abf95450-d1e1-448f-8b71-e6e6a5daef17">
