### ISSUE TITLE
请问会支持 vite 吗？

### ISSUE THREAD

**Issue by qinghuanI** [zthxxx/react-dev-inspector#23]

**Comment by zthxxx** [comment]
正在开发中，可能有不兼容 api 改动

**Comment by zthxxx** [comment]
@qinghuanI   react-dev-inspector@1.5.0  已支持

Docs see: https://github.com/zthxxx/react-dev-inspector#usage-with-vite2

Example see: https://github.com/zthxxx/react-dev-inspector/tree/master/sites/vite2
