### ISSUE TITLE
可以加一个 CHANGELOG 吗

### ISSUE THREAD

**Issue by nzreal** [zthxxx/react-dev-inspector#25]
老哥，聊了这么久，看了其他 issues 才发现你是中国人

**Comment by zthxxx** [comment]
我对用英语提的 issue 就会用英语回复啦，用中文提的 issue 就会用中文回啦，用日语提的 issue 就...就超过我能力了

**Comment by nzreal** [comment]
回到正题，我感觉需要加一个 CHANGELOG

**Comment by zthxxx** [comment]
最近没空

**Comment by nzreal** [comment]
你先忙~
