### ISSUE TITLE
提问：配置问题

### ISSUE THREAD

**Issue by TomJerryTheHandsome** [zthxxx/react-dev-inspector#27]
你好，我的项目配置是typescript，webpack使用ts-loader进行编译，请问babel-plugin是在ts-loader之前还是在之后呢

**Comment by zthxxx** [comment]
如果你的 jsx **不是**在 ts-loader 中编译，而是在 babel 中编译，那么 babel-loader, babel-plugin 在 ts-loader 之后，

如果 jsx 直接用 ts-loader 编译，那么需要 babel-loader 和 babel-plugin 在 ts-loader 之前 (但这样就没有用 ts-loader 的必要的了)

**Comment by zthxxx** [comment]
@TomJerryTheHandsome 或者给一下配置文件 / 项目地址我看看
