### ISSUE TITLE
无法唤起vscode

### ISSUE THREAD

**Issue by weibo785424079** [zthxxx/react-dev-inspector#28]
To set up the editor integration, add something like REACT_EDITOR=atom to the .env.local file in your project folder and restart the development server. Learn more: 老哥这是怎么回事啊？ 添加了REACT_EDITOR=code 也没用

**Comment by zthxxx** [comment]
![image](https://user-images.githubusercontent.com/15135943/111452575-a1b29900-874d-11eb-8cbd-988c0298ebfa.png)

**Comment by zthxxx** [comment]
@weibo785424079  上图里 vscode 的命令行工具装了吗？

**Comment by nzreal** [comment]
这让我想起我之前遇到的偶发问题，已经完成 Install 'code' command in PATH 以及将 export REACT_EDITOR=code 添加进了 ~/.zshrc，但是偶尔还是会有此报错，需要重新 Install 'code' command in PATH
