### ISSUE TITLE
Seems not working with cra@4.0.1 react@17.0.1

### ISSUE THREAD

**Issue by yokiijay** [zthxxx/react-dev-inspector#4]

**Comment by zthxxx** [comment]
@yokiijay  Maybe provide more context?  error trace, config, repo, and others

**Comment by sonacy** [comment]
@yokiijay https://github.com/sonacy/react-inspector-demo  这里有个demo，可以参考下. 是最新的cra版本。

**Comment by zthxxx** [comment]
@yokiijay  demo project with **create-react-app** & **customize-cra** see: 

https://github.com/zthxxx/react-dev-inspector/tree/master/sites/cra
