### ISSUE TITLE
windons的能用吗

### ISSUE THREAD

**Issue by zxlzzzz** [zthxxx/react-dev-inspector#56]
如题？

**Comment by zhangxiaolin999** [comment]
我用的是windons的vscode 不知道能不能用

**Comment by zthxxx** [comment]
可以的

**Comment by zhangxiaolin999** [comment]
好的 谢谢

**Comment by zhangxiaolin999** [comment]
![image](https://user-images.githubusercontent.com/43379189/117816066-b1a3b080-b298-11eb-869d-bfe922d6da6b.png)

**Comment by zhangxiaolin999** [comment]
我好想没有找到这个请求

**Comment by zhangxiaolin999** [comment]
组件是可以显示出来的

**Comment by zhangxiaolin999** [comment]
在浏览器请求是可以的
![image](https://user-images.githubusercontent.com/43379189/117907682-ca987a00-b309-11eb-907a-ae6394217a0b.png)

**Comment by zhangxiaolin999** [comment]
![image](https://user-images.githubusercontent.com/43379189/117908690-77272b80-b30b-11eb-9efd-5922fbd43f10.png)
![image](https://user-images.githubusercontent.com/43379189/117908714-80b09380-b30b-11eb-9d51-eb362c7bb574.png)

**Comment by zthxxx** [comment]
环境变量加了吗？
![image](https://user-images.githubusercontent.com/15135943/117920598-b5c7e080-b321-11eb-8ff5-8513ce870a2a.png)

**Comment by zhangxiaolin999** [comment]
在哪个目录 我找不到  我的是windows环境

**Comment by zthxxx** [comment]
[=> **win10 添加环境变量**](https://www.google.com/search?q=win10+%E6%B7%BB%E5%8A%A0%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F)

**Comment by zhangxiaolin999** [comment]
=_=！   这个是osx的写法   但是win环境怎么配置  可以指导一下吗

**Comment by zthxxx** [comment]
[![image](https://user-images.githubusercontent.com/15135943/117938614-cf752200-b339-11eb-863b-590d758b7299.png)](https://github.com/zthxxx/react-dev-inspector/issues/56#issuecomment-839501769)

如上，这是个可以点的链接

**Comment by zhangxiaolin999** [comment]
嗯嗯  看到了  环境变量的内容需要添加什么

**Comment by zthxxx** [comment]
![image](https://user-images.githubusercontent.com/15135943/117939450-a608c600-b33a-11eb-8a8e-7f88c61ceb47.png)

**Comment by zhangxiaolin999** [comment]
请问是配置系统环境变量还是用户环境变量?      变量名该如何写?      变量值为REACT_EDITOR=code  ?

**Comment by zhangxiaolin999** [comment]
你好   
![image](https://user-images.githubusercontent.com/43379189/117951349-aad37700-b346-11eb-80a2-6b4e9c4be1cf.png)

**Comment by zthxxx** [comment]
值就是 code   🤣

话说真的是做研发的么，配个环境变量这么难？ 😂  上面 taobao 的 npm 环境变量谁帮你配的？

**Comment by zhangxiaolin999** [comment]
我自己配的啊!

![image](https://user-images.githubusercontent.com/43379189/117953845-056dd280-b349-11eb-833a-73baeaad4f4d.png)

![image](https://user-images.githubusercontent.com/43379189/117953971-26362800-b349-11eb-85ca-b0900fcc563d.png)


没有响应😂

**Comment by zhangxiaolin999** [comment]
大佬啊  棒棒忙啊

**Comment by zthxxx** [comment]
截图放下 headers 请求参数和 response 呀

**Comment by zhangxiaolin999** [comment]
![image](https://user-images.githubusercontent.com/43379189/117956678-dc027600-b34b-11eb-8ae3-8abcdb2a4c85.png)

![image](https://user-images.githubusercontent.com/43379189/117956721-e755a180-b34b-11eb-8786-21dd7bbf7334.png)

**Comment by zhangxiaolin999** [comment]
![image](https://user-images.githubusercontent.com/43379189/117956778-f2a8cd00-b34b-11eb-852c-b85494d2cf13.png)

**Comment by zthxxx** [comment]
@zhangxiaolin999  点击之后，命令行有什么报错输出呢？

**Comment by zhangxiaolin999** [comment]
你好 我看了一下项目  命令行中没有报错 如图
![image](https://user-images.githubusercontent.com/43379189/118063899-8e7a1d80-b3cc-11eb-9187-4f5155511295.png)

**Comment by zxlzzzz** [comment]
你好 这是代码 链接: https://pan.baidu.com/s/15EeGCo1FJp0QE5SwFjQYRQ 提取码: v3i2 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by zthxxx** [comment]
我下载试了，把你写的 alert(1) alert(2) 删了直接跑，点击跳转正常

**Comment by zxlzzzz** [comment]
已经删除了 不能跳转呀

**Comment by zxlzzzz** [comment]
@zthxxx 麻烦把这条 issue 删掉
