### ISSUE TITLE
在基于icejs 的项目中的使用

### ISSUE THREAD

**Issue by CHOOSE6868** [zthxxx/react-dev-inspector#58]
你好,我们团队现在有个基于ice js的项目,我想尝试在其中此插件,但各种尝试配置折腾了半天后却无法生效.
大佬有空的时候可以看下在ice.js中如何使用吗,秋泥膏
配置如下:
ice.js 的配置文档:https://ice.alibaba-inc.com/docs/guide/basic/build
//build.config.js
```js
import { launchEditorMiddleware } from 'react-dev-inspector/plugins/webpack'
module.exports = {
    define: {
      env: process.env.NODE_ENV,
    },
    plugins: [
      ['build-plugin-fusion', {
        themePackage:"@alifd/theme-design-pro",
      }],
      (api) => {
        api.onGetWebpackConfig((config) => {
          config.entry('src/index.js');
        });
      },
      "@ali/build-plugin-ice-def",
    ],
    devServer: {
        before: (app) => {
          console.log('launchEditorMiddleware')
          app.use(launchEditorMiddleware)
        }
    },
    babelPlugins: [
        'react-dev-inspector/plugins/babel'
      ],
  }
```

**Comment by zthxxx** [comment]
这个文档 emmmm 是内网地址，外网没法访问

**Comment by zthxxx** [comment]
`<Inspector >` 组件在页面上加了吗？

**Comment by CHOOSE6868** [comment]
不好意思,发错了,这个是公网https://ice.work/docs/guide/basic/build

**Comment by CHOOSE6868** [comment]
加了的,按了快捷键后有提示,但是由于div上并没有行号和文件信息,所以看不到源码位置

**Comment by CHOOSE6868** [comment]
怀疑是babel插件没有生效,然后控制台也没有触发对应打开vscode的网络请求,我根据文档建立了个umi的项目,到是可以正常使用

**Comment by zthxxx** [comment]
react-dev-inspector 版本号多少？

**Comment by CHOOSE6868** [comment]
是默认的的1.5.3

**Comment by zthxxx** [comment]
> 不好意思,发错了,这个是公网https://ice.work/docs/guide/basic/build

我晚上起个 ice 项目试试

**Comment by zthxxx** [comment]
@CHOOSE6868  可能跟 babelPlugins 注册顺序有关，得在 babel 编译 jsx 语法之前

**Comment by CHOOSE6868** [comment]
是的,我看到掘金下面评论有说这个,但我在ice的配置没有看到有顺序配置,但好像默认配置的会放在插件列表最后,那就是默认最先执行

**Comment by zthxxx** [comment]
「好像默认配置的会放在插件列表最后」  这是最后执行吧，顺序不是反过来的

**Comment by CHOOSE6868** [comment]
🙈我搞错了,是的, presets才是与顺序相反,plugin是顺序的

**Comment by CHOOSE6868** [comment]
我搞定了老哥!是配置问题,等我有空提个pr写下解决办法❤️

**Comment by zthxxx** [comment]
@CHOOSE6868  好耶！

能不能先简单说说问题是啥？

**Comment by CHOOSE6868** [comment]
主要是在ice.js中他的webpack配置是使用webpack-chain,配置起来比较麻烦,等我写个ice.js的插件,这样就可以像umi一样使用了

**Comment by zthxxx** [comment]
所以问题还是 babel plugin 顺序优先级吗？

**Comment by CHOOSE6868** [comment]
是的,ice.js的那个配置比较“玄学了”😑,只能说对一般需求配置还是挺友好,特别定制就只能写插件

**Comment by zthxxx** [comment]
😂 噢噢，求有空写一个～
