### ISSUE TITLE
node版本兼容性问题

### ISSUE THREAD

**Issue by Rhuaer** [zthxxx/react-dev-inspector#6]
`package.json`中的node版本要求必须是`>=12.0.0`

这样低于`12.0.0`的项目都会安装失败

这样的版本要求是必须的吗？

**Comment by zthxxx** [comment]
是的

- Node 12 已经是长期支持版了，不应该用更早期的版本了
- Node 保证了都是后向兼容，所以你这边直接从 10.x 升级到 12.x 不会有什么问题，只有性能提升
