### ISSUE TITLE
app中间件的引用错误

### ISSUE THREAD

**Issue by wsz7777** [zthxxx/react-dev-inspector#7]
![image](https://user-images.githubusercontent.com/33828341/101331841-7c410400-38af-11eb-8449-ea3250f76b69.png)
另外建议 devServer 和 createLaunchEditorMiddleware 这里重点标注一下。看readme去配置webpack的时候直接忽略掉这一点了结果肯定没办法用。

**Comment by zthxxx** [comment]
@wsz7777  无法复现，能给下项目复现代码么？ 

我这里 install 之后 import 完全正常

![image](https://user-images.githubusercontent.com/15135943/101333536-b14e5600-38b1-11eb-9d16-02d2c8645516.png)

---

另外 devServer 和 middleware 这块已经完全是在最开头位置 **醒目标注** 了， 这还能忽略就确实是读的人的问题了

![image](https://user-images.githubusercontent.com/15135943/101333831-08ecc180-38b2-11eb-8662-a8c0527c3aba.png)

**Comment by zthxxx** [comment]
@wsz7777   `npm ls react-dev-inspector` 看看包版本多少呢

**Comment by wsz7777** [comment]
react-dev-inspector@1.0.10，是在ts中使用报错

**Comment by wsz7777** [comment]
![image](https://user-images.githubusercontent.com/33828341/101342102-0cd21100-38bd-11eb-9e4e-bf0232f92aa1.png)

**Comment by zthxxx** [comment]
> react-dev-inspector@1.0.10，是在ts中使用报错

@wsz7777  最新版本应该是 1.1.1 了，REDME 文档对应的是 1.1.1 的，所以升级一下就好了
