### ISSUE TITLE
react-dev-utils 版本可否升级到 v11

### ISSUE THREAD

**Issue by zzyifan** [zthxxx/react-dev-inspector#75]
现在的 v10.2.1 版本里面依赖的 immer 版本v1.10.0太低
![image](https://user-images.githubusercontent.com/694670/120983210-12e17580-c7ac-11eb-82b2-878454aaada2.png)

**Comment by zthxxx** [comment]
可以升级的，但是它的依赖中的 immer 版本低跟你使用有啥影响么？

**Comment by zzyifan** [comment]
> 可以升级的，但是它的依赖中的 immer 版本低跟你使用有啥影响么？

扫描工具识别低版本有安全隐患

**Comment by zthxxx** [comment]
@zzyifan 要不提一个 pr ？

**Comment by faradaytrs** [comment]
可以弄个dependabot然后每一个依赖一个一个处理

**Comment by zthxxx** [comment]
> 可以弄个dependabot然后每一个依赖一个一个处理

有的哦，可以看 PR 里一大堆

![image](https://user-images.githubusercontent.com/15135943/124700813-002f9d00-df20-11eb-9196-548f43df72f9.png)

**Comment by zthxxx** [comment]
@zzyifan   在 react-dev-inspector@1.7.0 中升级啦
