### ISSUE TITLE
node版本问题

### ISSUE THREAD

**Issue by weibo785424079** [zthxxx/react-dev-inspector#8]
node的版本必须12以上吗 
![image](https://user-images.githubusercontent.com/17724610/101752172-24eb9f80-3b0c-11eb-89ee-b74f0c72e4b2.png)

**Comment by zthxxx** [comment]
see https://github.com/zthxxx/react-dev-inspector/issues/6

![image](https://user-images.githubusercontent.com/15135943/101754114-56fe0100-3b0e-11eb-91cf-a9bc6e39262a.png)

**Comment by weibo785424079** [comment]
好的谢谢
