### ISSUE TITLE
微前端里使用失效

### ISSUE THREAD

**Issue by Nuyoah-ll** [zthxxx/react-dev-inspector#93]
qiankun结合react-dev-inspector，在主域中点击子项目的组件，不能打开vscode，不能自动定位组件所在代码。
但是如果单独打开子项目，点击组件，可以自定定位到所在代码。
有什么解决办法吗

**Comment by zthxxx** [comment]
@Nuyoah-ll  请给一个最小能复现的仓库

**Comment by lzzhy** [comment]
@Nuyoah-ll 请问有解决吗？我也遇到这种情况

**Comment by zthxxx** [comment]
@lzzhy  请给一个最小能复现的仓库

**Comment by zthxxx** [comment]
在微前端中使用，并且希望在**主项目**中启动也能定位**子项目**组件的话，

`<Inspector/>` 组件放在主项目中，且子项目使用 `@babel/preset-react` 配置 `development` 参数来给子项目组件添加源码**绝对路径**信息，(而非使用 `@react-dev-inspector/babel-plugin` 添加**相对路径**)，

这样主项目中打开可以正常定位和跳转子项目组件位置。

> babel plugin 对比描述见文档:  https://react-dev-inspector.zthxxx.me/docs/compiler-plugin#babel

最近在做的项目也是这样的场景，我的使用方式也和上面说的一样。
