### ISSUE TITLE
It is very hard to press 4 keys in the same time, how can I change it ?

### ISSUE THREAD

**Issue by jackchoumine** [zthxxx/react-dev-inspector#94]

**Comment by zthxxx** [comment]
@jackchoumine     https://github.com/zthxxx/react-dev-inspector#inspector-component-props

![image](https://user-images.githubusercontent.com/15135943/132802476-fbac8fbe-957d-4fd6-a761-e1cf1a60bfba.png)

![image](https://user-images.githubusercontent.com/15135943/132802523-d5061622-68a2-4004-8ea0-a64b65170ed9.png)
