### ISSUE TITLE
nextjs 项目中报错： SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by chenjiajing23** [zthxxx/react-dev-inspector#98]
[项目地址](https://github.com/chenjiajing23/next-example/commit/864639bd512afdbb4f79779681c7956bc1f7e2a4) 报错如下 （react-dev-inspector
Public版本 1.6.0）：
<img width="847" alt="截屏2021-09-22 00 34 33" src="https://user-images.githubusercontent.com/41351722/134210943-0aca97b6-3cff-446d-bba6-a16e77e4859d.png">

next.confing.js 
<img width="847" alt="截屏2021-09-22 00 37 33" src="https://user-images.githubusercontent.com/41351722/134211493-d4b36719-5ea7-45ce-98bf-fcbd3c396855.png">

**Comment by chenjiajing23** [comment]
https://githubmemory.com/repo/mahmoud-eskandari/NumToPersian/issues/16

**Comment by zthxxx** [comment]
@chenjiajing23 
`<Inspector />` 这个 react 组件 (`import { Inspector } from 'react-dev-inspector'` ) 不提供 cjs 产物，只提供了 esm 产物 (供 webpack / vite 等使用)，不支持 node 端使用，如 ssr

**Comment by chenjiajing23** [comment]
> @chenjiajing23
> `<Inspector />` 这个 react 组件 (`import { Inspector } from 'react-dev-inspector'` ) 不提供 cjs 产物，只提供了 esm 产物 (供 webpack / vite 等使用)，不支持 node 端使用，如 ssr

@zthxxx  感谢解答。自定义nextjs 服务，已解决这个了这问题了。需要两个操作 1. webapck 打包这个插件换成cjs 2. 自定义nextjs 服务。详情可以参考 https://github.com/chenjiajing23/next-example/commit/23a94480182d511657f79ce6ce12457654965d2c。

**Comment by zthxxx** [comment]
webpack 本身 resolver 直接支持 esm，不推荐使用 cjs

**Comment by chenjiajing23** [comment]
> webpack 本身 resolver 直接支持 esm，不推荐使用 cjs

nextjs 默认没有打包nodemodule 的东西，需要单独打包成cjs

**Comment by zthxxx** [comment]
使用 esm 是简单自然，特地配置把所有 esm 转为 cjs 可能是在把简单的事做复杂

**Comment by chenjiajing23** [comment]
> 使用 esm 是简单自然，特地配置把所有 esm 转为 cjs 可能是在把简单的事做复杂

是的。所以需要外部单独对此单独babel转成cjs。
<img width="1227" alt="截屏2021-09-22 12 03 13" src="https://user-images.githubusercontent.com/41351722/134281720-9cd4c307-8a30-4fa1-a726-032c98b8e147.png">
下

**Comment by zthxxx** [comment]
@chenjiajing23 方便说一下你的 node 、nextjs、webpack 版本是多少么

**Comment by chenjiajing23** [comment]
> @chenjiajing23 方便说一下你的 node 、nextjs、webpack 版本是多少么

node 14.6 nextjs 版本11左右 项目中有

**Comment by zthxxx** [comment]
看来 nextjs 上因为配套 ssr 的关系，用纯 esm 还是有些麻烦，我加一下 cjs 构建产物吧

**Comment by zthxxx** [comment]
@chenjiajing23   cjs 产物及 Next.js 支持已补充，见  [react-dev-inspector@v1.7.0](https://www.npmjs.com/package/react-dev-inspector/v/1.7.0)

docs: https://github.com/zthxxx/react-dev-inspector#usage-with-nextjs

example: https://github.com/zthxxx/react-dev-inspector/tree/master/examples/nextjs
